[build]
builder = "nixpacks"

[build.nixpacksPlan.variables]
NO_CACHE = "1"

[build.nixpacksPlan.phases.install]
cmds = ["npm install"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

